#!/usr/bin/env python3

import json
import sys
import requests
import pprint

if len(sys.argv) == 2:
	load_balancer_ip = sys.argv[1]
	server='http://'+ load_balancer_ip +':5000/fortune/'

	try:
		if (sys.argv[2]) == "cookie":
			r = requests.get(server)
			new = r.json()
			
			print(new)


		elif (sys.argv[2]) == "lottery":
			r = requests.get(server)
			new = r.json()
			
			print(new)


		elif (sys.argv[2]) == "both":
			r = requests.get(server)
			new = r.json()
			
			print(new)


		elif ((sys.argv[1]) == "help" or (sys.argv[1]) == "h"):
			print(
			"""
			type -help for help
			help: fortune <ip-load-balancer> <comando> 
			$ cookie : this argument will generate a fortune cookie
			$ lottery : this argument will generate a lottery number
			$ both   : get a pair cookie + lottery number
			"FORTUNE COOKIE generator"
			""")
		else:
			print(
			"""
			type -help for help
			help: fortune <ip-load-balancer> <comando> 
			$ cookie : this argument will generate a fortune cookie
			$ lottery : this argument will generate a lottery number
			$ both   : get a pair cookie + lottery number
			"FORTUNE COOKIE generator"
			""")
	except:
		print(
			"""
			"Ok something broke my bad (or not)"
			""")
else:
	print(
			"""
			type -help for help
			help: fortune <ip-load-balancer> <comando> 
			$ cookie : this argument will generate a fortune cookie
			$ lottery : this argument will generate a lottery number
			$ both   : get a pair cookie + lottery number
			"FORTUNE COOKIE generator"
			""")